platform :ios, '8.0'
use_frameworks!

def pods()
    pod 'Alamofire', '3.5.0'
    pod 'SwiftyJSON', '2.3.1'
    pod 'CryptoSwift', '0.5.2'
    pod 'XCGLogger', '3.1.1'
end

target 'SpendGoSDK' do
    pods()
end

target 'SpendGoSDKTests' do
    pods()
end
