package com.clp.model;

import java.io.Serializable;

import com.google.android.gms.location.Geofence;

public class CLPMobileSettings implements Serializable {

	private static final long serialVersionUID = 8138136422103486837L;
	public long DISTANCE_FILTER = 50;// in meters
	public float DISTANCE_STORE = 10000.0f;// in meters
	public float GEOFENCE_RADIUS = 750.0f;// in meters
	public float GEOFENCE_MIN_RADIUS = 150f;// in meters
	public long STORE_REFRESH_TIME = 900;// in seconds
	public int MAX_STORE_COUNT_ANDROID = 70;
	public int MAX_BEACON_COUNT = 15;
	public int ENABLE_LOCAL_NOTIFICATION = 0;// 1- yes 0- No
	public long OUT_SIDE_UPDATE_INTERVAL = 500;// in seconds
	public long OUT_SIDE_FASTEST_UPDATE_INTERVAL = 300;//in seconds
	public long IN_SIDE_UPDATE_INTERVAL = 60;//in seconds
	public long IN_SIDE_FASTEST_UPDATE_INTERVAL = 30;//in seconds
	public long IN_STORE_UPDATE_INTERVAL = 300;//in seconds
	public long GEOFENCE_CHECK_FREQUENCY = 1800;//in seconds
	public long LOCATION_UPDATE_PING_FREQUENCY = 15;
	public long BEACON_PING_FREQUENCY = 30;//in seconds
	public long GEOFENCE_EXPIRY_TIME = Geofence.NEVER_EXPIRE;//
	public long IN_REGION_SLAB_TIME = 500;//in seconds

	public long LOCATION_SERVICE_REFRESH_TIME = 900;
	public long GEOFENCE_CHECK_DISTANCE_MOVED=300;//in meters
	public long BEACON_SLAB_TIME=2500;//in sec
	public int TRIGGER_APP_EVENTS=0;// 1 on / 0 off
	public int TRIGGER_GEOFENCE=0;//1 on / 0 off
	public int TRIGGER_BEACON=0;//1 on / 0 off
	public int TRIGGER_ERROR_EVENT=0;//1 on / 0 off
	public int TRIGGER_PUSH_NOTIFICATION=0;//1 on / 0 off
	public int TRIGGER_INAPPOFFER_ENABLED=0;//1 on / 0 off
	public   int   EVENT_QUEUE_SIZE_THRESHOLD=10;
	public   int   TIMER_DELAY_IN_SECONDS=5;
	public String VERSION="2.2.2";
	public String INFORMATION="New version of app is available now in app store. For better experience please update the application";
	public String FORCEUPDATE="0";
	public int FREQUENCY=2;
	public CLPMobileSettings() {
	};


	public String getVERSION() {
		return VERSION;
	}


	public void setVERSION(String vERSION) {
		VERSION = vERSION;
	}


	public String getINFORMATION() {
		return INFORMATION;
	}


	public void setINFORMATION(String iNFORMATION) {
		INFORMATION = iNFORMATION;
	}





	public String getFORCEUPDATE() {
		return FORCEUPDATE;
	}


	public void setFORCEUPDATE(String fORCEUPDATE) {
		FORCEUPDATE = fORCEUPDATE;
	}


	public int getFREQUENCY() {
		return FREQUENCY;
	}


	public void setFREQUENCY(int fREQUENCY) {
		FREQUENCY = fREQUENCY;
	}


	public CLPMobileSettings(long dISTANCE_FILTER, float dISTANCE_STORE,
			float gEOFENCE_RADIUS, float gEOFENCE_MIN_RADIUS,
			long sTORE_REFRESH_TIME, int mAX_STORE_COUNT_ANDROID, int mAX_BEACON_COUNT,
			int eNABLE_LOCAL_NOTIFICATION, long oUT_SIDE_UPDATE_INTERVAL,
			long oUT_SIDE_FASTEST_UPDATE_INTERVAL,
			long iN_SIDE_UPDATE_INTERVAL, long iN_SIDE_FASTEST_UPDATE_INTERVAL,
			long gEOFENCE_CHECK_FREQUENCY, long lOCATION_UPDATE_PING_FREQUENCY,
			long bEACON_PING_FREQUENCY, long gEOFENCE_EXPIRY_TIME,
			long iN_REGION_SLAB_TIME, long lOCATION_SERVICE_REFRESH_TIME,
			long iIN_STORE_UPDATE_INTERVAL, long gEOFENCE_CHECK_DISTANCE_MOVED,long bEACON_SLAB_TIME,
			int tRIGGER_APP_EVENTS,
			int tRIGGER_GEOFENCE,
			int tRIGGER_BEACON,
			int tRIGGER_ERROR_EVENT,
			int tRIGGER_PUSH_NOTIFICATION,
			int tRIGGER_INAPPOFFER_ENABLED,
			int eVENT_QUEUE_SIZE_THRESHOLD,
			int tIMER_DELAY_IN_SECONDS) {
		super();
		this.DISTANCE_FILTER = dISTANCE_FILTER;
		this.DISTANCE_STORE = dISTANCE_STORE;
		this.GEOFENCE_RADIUS = gEOFENCE_RADIUS;
		this.GEOFENCE_MIN_RADIUS = gEOFENCE_MIN_RADIUS;
		this.STORE_REFRESH_TIME = sTORE_REFRESH_TIME;
		this.MAX_STORE_COUNT_ANDROID = mAX_STORE_COUNT_ANDROID;
		this.MAX_BEACON_COUNT = mAX_BEACON_COUNT;
		this.ENABLE_LOCAL_NOTIFICATION = eNABLE_LOCAL_NOTIFICATION;
		this.OUT_SIDE_UPDATE_INTERVAL = oUT_SIDE_UPDATE_INTERVAL;
		this.OUT_SIDE_FASTEST_UPDATE_INTERVAL = oUT_SIDE_FASTEST_UPDATE_INTERVAL;
		this.IN_SIDE_UPDATE_INTERVAL = iN_SIDE_UPDATE_INTERVAL;
		this.IN_SIDE_FASTEST_UPDATE_INTERVAL = iN_SIDE_FASTEST_UPDATE_INTERVAL;
		this.GEOFENCE_CHECK_FREQUENCY = gEOFENCE_CHECK_FREQUENCY;
		this.LOCATION_UPDATE_PING_FREQUENCY = lOCATION_UPDATE_PING_FREQUENCY;
		this.BEACON_PING_FREQUENCY = bEACON_PING_FREQUENCY;
		this.GEOFENCE_EXPIRY_TIME = gEOFENCE_EXPIRY_TIME;
		this.IN_REGION_SLAB_TIME = iN_REGION_SLAB_TIME;
		this.LOCATION_SERVICE_REFRESH_TIME = lOCATION_SERVICE_REFRESH_TIME;
		this.IN_STORE_UPDATE_INTERVAL = iIN_STORE_UPDATE_INTERVAL;
		this.GEOFENCE_CHECK_DISTANCE_MOVED=gEOFENCE_CHECK_DISTANCE_MOVED;
		this.BEACON_SLAB_TIME=bEACON_SLAB_TIME;
		this.TRIGGER_APP_EVENTS=tRIGGER_APP_EVENTS;
		this.TRIGGER_BEACON=tRIGGER_BEACON;
		this.TRIGGER_ERROR_EVENT=tRIGGER_ERROR_EVENT;
		this.TRIGGER_GEOFENCE=tRIGGER_GEOFENCE;
		this.TRIGGER_PUSH_NOTIFICATION=tRIGGER_PUSH_NOTIFICATION;
		this.TRIGGER_INAPPOFFER_ENABLED=tRIGGER_INAPPOFFER_ENABLED;
		this.TIMER_DELAY_IN_SECONDS=tIMER_DELAY_IN_SECONDS;
		this.EVENT_QUEUE_SIZE_THRESHOLD=eVENT_QUEUE_SIZE_THRESHOLD;

	}

	public int getTRIGGER_INAPPOFFER_ENABLED() {
		return TRIGGER_INAPPOFFER_ENABLED;
	}


	public void setTRIGGER_INAPPOFFER_ENABLED(int tRIGGER_INAPPOFFER_ENABLED) {
		TRIGGER_INAPPOFFER_ENABLED = tRIGGER_INAPPOFFER_ENABLED;
	}


	public int getEVENT_QUEUE_SIZE_THRESHOLD() {
		return EVENT_QUEUE_SIZE_THRESHOLD;
	}


	public void setEVENT_QUEUE_SIZE_THRESHOLD(int eVENT_QUEUE_SIZE_THRESHOLD) {
		EVENT_QUEUE_SIZE_THRESHOLD = eVENT_QUEUE_SIZE_THRESHOLD;
	}


	public int getTIMER_DELAY_IN_SECONDS() {
		return TIMER_DELAY_IN_SECONDS;
	}


	public void setTIMER_DELAY_IN_SECONDS(int tIMER_DELAY_IN_SECONDS) {
		TIMER_DELAY_IN_SECONDS = tIMER_DELAY_IN_SECONDS;
	}


	public int getTRIGGER_GEOFENCE() {
		return TRIGGER_GEOFENCE;
	}



	public void setTRIGGER_GEOFENCE(int tRIGGER_GEOFENCE) {
		TRIGGER_GEOFENCE = tRIGGER_GEOFENCE;
	}



	public int getTRIGGER_BEACON() {
		return TRIGGER_BEACON;
	}



	public void setTRIGGER_BEACON(int tRIGGER_BEACON) {
		TRIGGER_BEACON = tRIGGER_BEACON;
	}



	public int getTRIGGER_ERROR_EVENT() {
		return TRIGGER_ERROR_EVENT;
	}



	public void setTRIGGER_ERROR_EVENT(int tRIGGER_ERROR_EVENT) {
		TRIGGER_ERROR_EVENT = tRIGGER_ERROR_EVENT;
	}



	public int getTRIGGER_PUSH_NOTIFICATION() {
		return TRIGGER_PUSH_NOTIFICATION;
	}



	public void setTRIGGER_PUSH_NOTIFICATION(int tRIGGER_PUSH_NOTIFICATION) {
		TRIGGER_PUSH_NOTIFICATION = tRIGGER_PUSH_NOTIFICATION;
	}



	public void setTRIGGER_APP_EVENTS(int tRIGGER_APP_EVENTS) {
		TRIGGER_APP_EVENTS = tRIGGER_APP_EVENTS;
	}



	public int getTRIGGER_APP_EVENTS() {
		return TRIGGER_APP_EVENTS;
	}
	public long getDISTANCE_FILTER() {
		return DISTANCE_FILTER;
	}

	public float getDISTANCE_STORE() {
		return DISTANCE_STORE;
	}

	public float getGEOFENCE_RADIUS() {
		return GEOFENCE_RADIUS;
	}

	public float getGEOFENCE_MIN_RADIUS() {
		return GEOFENCE_MIN_RADIUS;
	}

	public long getSTORE_REFRESH_TIME() {
		return STORE_REFRESH_TIME;
	}

	public int getMAX_STORE_COUNT_ANDROID() {
		return MAX_STORE_COUNT_ANDROID;
	}

	public int getMAX_BEACON_COUNT() {
		return MAX_BEACON_COUNT;
	}

	public int getENABLE_LOCAL_NOTIFICATION() {
		return ENABLE_LOCAL_NOTIFICATION;
	}

	public long getOUT_SIDE_UPDATE_INTERVAL() {
		return OUT_SIDE_UPDATE_INTERVAL;
	}

	public long getOUT_SIDE_FASTEST_UPDATE_INTERVAL() {
		return OUT_SIDE_FASTEST_UPDATE_INTERVAL;
	}

	public long getIN_SIDE_UPDATE_INTERVAL() {
		return IN_SIDE_UPDATE_INTERVAL;
	}

	public long getIN_SIDE_FASTEST_UPDATE_INTERVAL() {
		return IN_SIDE_FASTEST_UPDATE_INTERVAL;
	}

	public long getGEOFENCE_CHECK_FREQUENCY() {
		return GEOFENCE_CHECK_FREQUENCY;
	}

	public long getLOCATION_UPDATE_PING_FREQUENCY() {
		return LOCATION_UPDATE_PING_FREQUENCY;
	}

	public long getBEACON_PING_FREQUENCY() {
		return BEACON_PING_FREQUENCY;
	}

	public long getGEOFENCE_EXPIRY_TIME() {
		return GEOFENCE_EXPIRY_TIME;
	}

	public long getIN_REGION_SLAB_TIME() {
		return IN_REGION_SLAB_TIME;
	}

	public long getLOCATION_SERVICE_REFRESH_TIME() {
		return LOCATION_SERVICE_REFRESH_TIME;
	}

	public long getIN_STORE_UPDATE_INTERVAL() {
		return IN_STORE_UPDATE_INTERVAL;
	}

	public long getGEOFENCE_CHECK_DISTANCE_MOVED() {
		return GEOFENCE_CHECK_DISTANCE_MOVED;
	}

	public long getBEACON_SLAB_TIME() {
		return BEACON_SLAB_TIME;
	}

	public void setBEACON_SLAB_TIME(long bEACON_SLAB_TIME) {
		BEACON_SLAB_TIME = bEACON_SLAB_TIME;
	}

}
