platform :ios, '8.0'
use_frameworks!

def pods()
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'CryptoSwift'
    pod 'XCGLogger'
end

target 'SpendGoSDK' do
    pods()
end

target 'SpendGoSDKTests' do
    pods()
end
