package com.clp.model;

import java.io.Serializable;

import com.google.android.gms.location.Geofence;

public class CLPMobileSettings implements Serializable {

	private static final long serialVersionUID = -1234567890123456794L;

	public long DISTANCE_FILTER = 50;// in meters
	public float DISTANCE_STORE = 10000.0f;// in meters
	public float GEOFENCE_RADIUS = 750.0f;// in meters
	public float GEOFENCE_MIN_RADIUS = 150f;// in meters
	public long STORE_REFRESH_TIME = 900;// in seconds
	public int MAX_STORE_COUNT_ANDROID = 70;
	public int MAX_BEACON_COUNT = 15;
	public int ENABLE_LOCAL_NOTIFICATION = 0;// 1- yes 0- No
	public long OUT_SIDE_UPDATE_INTERVAL = 500;// in seconds
	public long OUT_SIDE_FASTEST_UPDATE_INTERVAL = 300;//in seconds
	public long IN_SIDE_UPDATE_INTERVAL = 60;//in seconds
	public long IN_SIDE_FASTEST_UPDATE_INTERVAL = 30;//in seconds
	public long IN_STORE_UPDATE_INTERVAL = 300;//in seconds
	public long GEOFENCE_CHECK_FREQUENCY = 1800;//in seconds
	public long LOCATION_UPDATE_PING_FREQUENCY = 15;
	public long BEACON_PING_FREQUENCY = 30;//in seconds
	public long GEOFENCE_EXPIRY_TIME = Geofence.NEVER_EXPIRE;//
	public long IN_REGION_SLAB_TIME = 500;//in seconds

	public long LOCATION_SERVICE_REFRESH_TIME = 900;
	public long GEOFENCE_CHECK_DISTANCE_MOVED=300;//in meters
	public long BEACON_SLAB_TIME=2500;//in sec

	public CLPMobileSettings() {
	};

	public CLPMobileSettings(long dISTANCE_FILTER, float dISTANCE_STORE,
			float gEOFENCE_RADIUS, float gEOFENCE_MIN_RADIUS,
			long sTORE_REFRESH_TIME, int mAX_STORE_COUNT_ANDROID, int mAX_BEACON_COUNT,
			int eNABLE_LOCAL_NOTIFICATION, long oUT_SIDE_UPDATE_INTERVAL,
			long oUT_SIDE_FASTEST_UPDATE_INTERVAL,
			long iN_SIDE_UPDATE_INTERVAL, long iN_SIDE_FASTEST_UPDATE_INTERVAL,
			long gEOFENCE_CHECK_FREQUENCY, long lOCATION_UPDATE_PING_FREQUENCY,
			long bEACON_PING_FREQUENCY, long gEOFENCE_EXPIRY_TIME,
			long iN_REGION_SLAB_TIME, long lOCATION_SERVICE_REFRESH_TIME,
			long iIN_STORE_UPDATE_INTERVAL, long gEOFENCE_CHECK_DISTANCE_MOVED,long bEACON_SLAB_TIME) {
		super();
		this.DISTANCE_FILTER = dISTANCE_FILTER;
		this.DISTANCE_STORE = dISTANCE_STORE;
		this.GEOFENCE_RADIUS = gEOFENCE_RADIUS;
		this.GEOFENCE_MIN_RADIUS = gEOFENCE_MIN_RADIUS;
		this.STORE_REFRESH_TIME = sTORE_REFRESH_TIME;
		this.MAX_STORE_COUNT_ANDROID = mAX_STORE_COUNT_ANDROID;
		this.MAX_BEACON_COUNT = mAX_BEACON_COUNT;
		this.ENABLE_LOCAL_NOTIFICATION = eNABLE_LOCAL_NOTIFICATION;
		this.OUT_SIDE_UPDATE_INTERVAL = oUT_SIDE_UPDATE_INTERVAL;
		this.OUT_SIDE_FASTEST_UPDATE_INTERVAL = oUT_SIDE_FASTEST_UPDATE_INTERVAL;
		this.IN_SIDE_UPDATE_INTERVAL = iN_SIDE_UPDATE_INTERVAL;
		this.IN_SIDE_FASTEST_UPDATE_INTERVAL = iN_SIDE_FASTEST_UPDATE_INTERVAL;
		this.GEOFENCE_CHECK_FREQUENCY = gEOFENCE_CHECK_FREQUENCY;
		this.LOCATION_UPDATE_PING_FREQUENCY = lOCATION_UPDATE_PING_FREQUENCY;
		this.BEACON_PING_FREQUENCY = bEACON_PING_FREQUENCY;
		this.GEOFENCE_EXPIRY_TIME = gEOFENCE_EXPIRY_TIME;
		this.IN_REGION_SLAB_TIME = iN_REGION_SLAB_TIME;
		this.LOCATION_SERVICE_REFRESH_TIME = lOCATION_SERVICE_REFRESH_TIME;
		this.IN_STORE_UPDATE_INTERVAL = iIN_STORE_UPDATE_INTERVAL;
		this.GEOFENCE_CHECK_DISTANCE_MOVED=gEOFENCE_CHECK_DISTANCE_MOVED;
		this.BEACON_SLAB_TIME=bEACON_SLAB_TIME;
	}

	public long getDISTANCE_FILTER() {
		return DISTANCE_FILTER;
	}

	public float getDISTANCE_STORE() {
		return DISTANCE_STORE;
	}

	public float getGEOFENCE_RADIUS() {
		return GEOFENCE_RADIUS;
	}

	public float getGEOFENCE_MIN_RADIUS() {
		return GEOFENCE_MIN_RADIUS;
	}

	public long getSTORE_REFRESH_TIME() {
		return STORE_REFRESH_TIME;
	}

	public int getMAX_STORE_COUNT_ANDROID() {
		return MAX_STORE_COUNT_ANDROID;
	}

	public int getMAX_BEACON_COUNT() {
		return MAX_BEACON_COUNT;
	}

	public int getENABLE_LOCAL_NOTIFICATION() {
		return ENABLE_LOCAL_NOTIFICATION;
	}

	public long getOUT_SIDE_UPDATE_INTERVAL() {
		return OUT_SIDE_UPDATE_INTERVAL;
	}

	public long getOUT_SIDE_FASTEST_UPDATE_INTERVAL() {
		return OUT_SIDE_FASTEST_UPDATE_INTERVAL;
	}

	public long getIN_SIDE_UPDATE_INTERVAL() {
		return IN_SIDE_UPDATE_INTERVAL;
	}

	public long getIN_SIDE_FASTEST_UPDATE_INTERVAL() {
		return IN_SIDE_FASTEST_UPDATE_INTERVAL;
	}

	public long getGEOFENCE_CHECK_FREQUENCY() {
		return GEOFENCE_CHECK_FREQUENCY;
	}

	public long getLOCATION_UPDATE_PING_FREQUENCY() {
		return LOCATION_UPDATE_PING_FREQUENCY;
	}

	public long getBEACON_PING_FREQUENCY() {
		return BEACON_PING_FREQUENCY;
	}

	public long getGEOFENCE_EXPIRY_TIME() {
		return GEOFENCE_EXPIRY_TIME;
	}

	public long getIN_REGION_SLAB_TIME() {
		return IN_REGION_SLAB_TIME;
	}

	public long getLOCATION_SERVICE_REFRESH_TIME() {
		return LOCATION_SERVICE_REFRESH_TIME;
	}

	public long getIN_STORE_UPDATE_INTERVAL() {
		return IN_STORE_UPDATE_INTERVAL;
	}

	public long getGEOFENCE_CHECK_DISTANCE_MOVED() {
		return GEOFENCE_CHECK_DISTANCE_MOVED;
	}

	public long getBEACON_SLAB_TIME() {
		return BEACON_SLAB_TIME;
	}

	public void setBEACON_SLAB_TIME(long bEACON_SLAB_TIME) {
		BEACON_SLAB_TIME = bEACON_SLAB_TIME;
	}

}
