platform :ios, '8.0'
use_frameworks!

target 'InCommSDK' do
  pod 'Alamofire', '3.5.0'
  pod 'SwiftyJSON', '2.3.1'
  pod 'CryptoSwift', '0.5.2'
end

target 'InCommSDKTests' do
  pod 'Alamofire', '3.5.0'
  pod 'SwiftyJSON', '2.3.1'
  pod 'CryptoSwift', '0.5.2'
end
