source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

def pods()
    pod 'HDK', :path => '../HWAY_HDK_iOS'
    pod 'OloSDK', :path => '../JMBA_Olo_iOS_SDK'
    pod 'SpendGoSDK', :path => '../JMBA_SpendGo_iOS_SDK'
    pod 'InCommSDK', :path => '../JMBA_InComm_iOS_SDK'
    pod 'Spring', :git => 'git@github.com:MengTo/Spring.git', :branch => 'swift2'
    pod 'CryptoSwift', '0.5.2'
    pod 'Alamofire', '3.5.0'
    pod 'SwiftyJSON', '2.3.1'
    pod 'Parse', '1.13.0'
    pod 'HanekeSwift', '0.10.1'
    pod 'SVProgressHUD', '1.1.3'
    pod 'Instabug', '4.1.7'
    pod 'XCGLogger', '3.1.1'
    pod 'MGSwipeTableCell', '1.5.3'
    pod 'AppsFlyerFramework', '4.5.3'
    pod 'CardIO', '5.4.1'
end

target "JambaJuice" do
   pods()
end

target "JambaJuiceTests" do
   pods()
end

