# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

def pods()
	pod 'Alamofire', '3.5.0'
    pod 'SwiftyJSON', '2.3.1'
    pod 'XCGLogger', '3.1.1'
end

target 'Olo' do
    pods()
end

target 'OloTests' do
    pods()
end
