language: objective-c
osx_image: xcode7

before_script: 
- set -e
- gem install xcpretty

script:
- set -o pipefail && xcodebuild -workspace JambaJuice.xcworkspace -scheme JambaJuice clean test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c

notifications:
  slack: hathway:iXTYkaD3E7h3AsUJBOeq4qt6

